version: '3.1'

services:

  mongo_db:
    image: mongo:7.0.6
    volumes:
      - mongo_data:/data/mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - mongo_db_network

  rabbitmq:
    container_name: rabbitmq_container
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mongo_db_network
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json

  order_processing_api:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    restart: always
    environment:
      MONGO_DB_URI: mongodb://mongo_db:27017/orders_system_db
      RABBITMQ_HOST: rabbitmq_container
    ports:
      - "8080:8080"
      - "9000:9000"
    depends_on:
      - mongo_db
      - rabbitmq
    networks:
      - mongo_db_network

networks:
  mongo_db_network:
    driver: bridge

volumes:
  mongo_data: