version: '3.1'

services:

    mongo_db:
        image: mongo:7.0.6
        volumes:
          - mongo_data:/data/mongo
        ports:
            - "27017:27017"
        restart: unless-stopped

    user_management_api:
        build: .
        restart: always
        environment:
            MONGO_DB_URI: mongodb://mongo_db:27017/orders_system_db
        ports:
            - "8080:8080"
        depends_on:
            - mongo_db

volumes:
    mongo_data: