version: '3.1'

services:

  mongo_db:
    image: mongo:7.0.6
    volumes:
      - mongo_data:/data/mongo
    restart: unless-stopped

  restaurant_management_api:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    restart: always
    environment:
      MONGO_DB_URI: mongodb://mongo_db:27017/restaurant_db
    ports:
      - "8082:8080"
    depends_on:
      - mongo_db

volumes:
  mongo_data: