name: Run unit tests

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*'
      - '!README.md'

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: 7.0.6

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and test User Management API
      working-directory: ./UserManagementAPI
      run: mvn -B package --file pom.xml

    - name: Setup Gradle 8.5
      working-directory: ./OrderProcessingAPI
      run: |
        gradle wrapper --gradle-version 8.5
        chmod +x gradlew
    
    - name: Build Orders gRPC API
      working-directory: ./UserManagementAPI
      run: ./gradlew build
    
    - name: Test Orders gRPC API
      working-directory: ./UserManagementAPI
      run: ./gradlew test
